---
base_url: https://example.com
title: example
description: This website is powered by HyperTemplates.
author:
    href: /
    name: example
    username: '@example.com'
    favicon: /favicon.png
favicon:
    href: /favicon.png
config:
    builds_dir: builds
    content_dir: content
    data_dir: data
    deployments_dir: deployments
    drafts_dir: drafts
    static_dir: static
    theme: theme.json
    tag_layout: default
    tag_path: /tags
    tidy_mode: true
